# Generated by Django 2.1.1 on 2018-09-25 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InscriptionForm',
        ),
    ]
