# Generated by Django 2.1.1 on 2018-09-22 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20180922_0112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
